version: "3.8"

services:
  app:
    build: .
    ports:
      - "8888:8080"
    environment:
      - CATALINA_OPTS=-Xmx512m
    volumes:
      - xml_data:/root/xmw_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/EXA"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  xml_data:
    driver: local
