/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExaIndexLazyImport = createFileRoute('/exa/')()
const ExaUiIndexLazyImport = createFileRoute('/exa/ui/')()
const ExaUiLecturersIndexLazyImport = createFileRoute('/exa/ui/lecturers/')()
const ExaUiExamsIndexLazyImport = createFileRoute('/exa/ui/exams/')()
const ExaUiCoursesIndexLazyImport = createFileRoute('/exa/ui/courses/')()
const ExaUiLecturersNewLazyImport = createFileRoute('/exa/ui/lecturers/new')()
const ExaUiExamsNewLazyImport = createFileRoute('/exa/ui/exams/new')()
const ExaUiCoursesNewLazyImport = createFileRoute('/exa/ui/courses/new')()

// Create/Update Routes

const ExaIndexLazyRoute = ExaIndexLazyImport.update({
  id: '/exa/',
  path: '/exa/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/index.lazy').then((d) => d.Route))

const ExaUiIndexLazyRoute = ExaUiIndexLazyImport.update({
  id: '/exa/ui/',
  path: '/exa/ui/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/ui/index.lazy').then((d) => d.Route))

const ExaUiLecturersIndexLazyRoute = ExaUiLecturersIndexLazyImport.update({
  id: '/exa/ui/lecturers/',
  path: '/exa/ui/lecturers/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/lecturers/index.lazy').then((d) => d.Route),
)

const ExaUiExamsIndexLazyRoute = ExaUiExamsIndexLazyImport.update({
  id: '/exa/ui/exams/',
  path: '/exa/ui/exams/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/exams/index.lazy').then((d) => d.Route),
)

const ExaUiCoursesIndexLazyRoute = ExaUiCoursesIndexLazyImport.update({
  id: '/exa/ui/courses/',
  path: '/exa/ui/courses/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/courses/index.lazy').then((d) => d.Route),
)

const ExaUiLecturersNewLazyRoute = ExaUiLecturersNewLazyImport.update({
  id: '/exa/ui/lecturers/new',
  path: '/exa/ui/lecturers/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/lecturers/new.lazy').then((d) => d.Route),
)

const ExaUiExamsNewLazyRoute = ExaUiExamsNewLazyImport.update({
  id: '/exa/ui/exams/new',
  path: '/exa/ui/exams/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/exams/new.lazy').then((d) => d.Route),
)

const ExaUiCoursesNewLazyRoute = ExaUiCoursesNewLazyImport.update({
  id: '/exa/ui/courses/new',
  path: '/exa/ui/courses/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/courses/new.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exa/': {
      id: '/exa/'
      path: '/exa'
      fullPath: '/exa'
      preLoaderRoute: typeof ExaIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/': {
      id: '/exa/ui/'
      path: '/exa/ui'
      fullPath: '/exa/ui'
      preLoaderRoute: typeof ExaUiIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/courses/new': {
      id: '/exa/ui/courses/new'
      path: '/exa/ui/courses/new'
      fullPath: '/exa/ui/courses/new'
      preLoaderRoute: typeof ExaUiCoursesNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/exams/new': {
      id: '/exa/ui/exams/new'
      path: '/exa/ui/exams/new'
      fullPath: '/exa/ui/exams/new'
      preLoaderRoute: typeof ExaUiExamsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/lecturers/new': {
      id: '/exa/ui/lecturers/new'
      path: '/exa/ui/lecturers/new'
      fullPath: '/exa/ui/lecturers/new'
      preLoaderRoute: typeof ExaUiLecturersNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/courses/': {
      id: '/exa/ui/courses/'
      path: '/exa/ui/courses'
      fullPath: '/exa/ui/courses'
      preLoaderRoute: typeof ExaUiCoursesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/exams/': {
      id: '/exa/ui/exams/'
      path: '/exa/ui/exams'
      fullPath: '/exa/ui/exams'
      preLoaderRoute: typeof ExaUiExamsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/lecturers/': {
      id: '/exa/ui/lecturers/'
      path: '/exa/ui/lecturers'
      fullPath: '/exa/ui/lecturers'
      preLoaderRoute: typeof ExaUiLecturersIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/exa': typeof ExaIndexLazyRoute
  '/exa/ui': typeof ExaUiIndexLazyRoute
  '/exa/ui/courses/new': typeof ExaUiCoursesNewLazyRoute
  '/exa/ui/exams/new': typeof ExaUiExamsNewLazyRoute
  '/exa/ui/lecturers/new': typeof ExaUiLecturersNewLazyRoute
  '/exa/ui/courses': typeof ExaUiCoursesIndexLazyRoute
  '/exa/ui/exams': typeof ExaUiExamsIndexLazyRoute
  '/exa/ui/lecturers': typeof ExaUiLecturersIndexLazyRoute
}

export interface FileRoutesByTo {
  '/exa': typeof ExaIndexLazyRoute
  '/exa/ui': typeof ExaUiIndexLazyRoute
  '/exa/ui/courses/new': typeof ExaUiCoursesNewLazyRoute
  '/exa/ui/exams/new': typeof ExaUiExamsNewLazyRoute
  '/exa/ui/lecturers/new': typeof ExaUiLecturersNewLazyRoute
  '/exa/ui/courses': typeof ExaUiCoursesIndexLazyRoute
  '/exa/ui/exams': typeof ExaUiExamsIndexLazyRoute
  '/exa/ui/lecturers': typeof ExaUiLecturersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/exa/': typeof ExaIndexLazyRoute
  '/exa/ui/': typeof ExaUiIndexLazyRoute
  '/exa/ui/courses/new': typeof ExaUiCoursesNewLazyRoute
  '/exa/ui/exams/new': typeof ExaUiExamsNewLazyRoute
  '/exa/ui/lecturers/new': typeof ExaUiLecturersNewLazyRoute
  '/exa/ui/courses/': typeof ExaUiCoursesIndexLazyRoute
  '/exa/ui/exams/': typeof ExaUiExamsIndexLazyRoute
  '/exa/ui/lecturers/': typeof ExaUiLecturersIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/exa'
    | '/exa/ui'
    | '/exa/ui/courses/new'
    | '/exa/ui/exams/new'
    | '/exa/ui/lecturers/new'
    | '/exa/ui/courses'
    | '/exa/ui/exams'
    | '/exa/ui/lecturers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/exa'
    | '/exa/ui'
    | '/exa/ui/courses/new'
    | '/exa/ui/exams/new'
    | '/exa/ui/lecturers/new'
    | '/exa/ui/courses'
    | '/exa/ui/exams'
    | '/exa/ui/lecturers'
  id:
    | '__root__'
    | '/exa/'
    | '/exa/ui/'
    | '/exa/ui/courses/new'
    | '/exa/ui/exams/new'
    | '/exa/ui/lecturers/new'
    | '/exa/ui/courses/'
    | '/exa/ui/exams/'
    | '/exa/ui/lecturers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ExaIndexLazyRoute: typeof ExaIndexLazyRoute
  ExaUiIndexLazyRoute: typeof ExaUiIndexLazyRoute
  ExaUiCoursesNewLazyRoute: typeof ExaUiCoursesNewLazyRoute
  ExaUiExamsNewLazyRoute: typeof ExaUiExamsNewLazyRoute
  ExaUiLecturersNewLazyRoute: typeof ExaUiLecturersNewLazyRoute
  ExaUiCoursesIndexLazyRoute: typeof ExaUiCoursesIndexLazyRoute
  ExaUiExamsIndexLazyRoute: typeof ExaUiExamsIndexLazyRoute
  ExaUiLecturersIndexLazyRoute: typeof ExaUiLecturersIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  ExaIndexLazyRoute: ExaIndexLazyRoute,
  ExaUiIndexLazyRoute: ExaUiIndexLazyRoute,
  ExaUiCoursesNewLazyRoute: ExaUiCoursesNewLazyRoute,
  ExaUiExamsNewLazyRoute: ExaUiExamsNewLazyRoute,
  ExaUiLecturersNewLazyRoute: ExaUiLecturersNewLazyRoute,
  ExaUiCoursesIndexLazyRoute: ExaUiCoursesIndexLazyRoute,
  ExaUiExamsIndexLazyRoute: ExaUiExamsIndexLazyRoute,
  ExaUiLecturersIndexLazyRoute: ExaUiLecturersIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/exa/",
        "/exa/ui/",
        "/exa/ui/courses/new",
        "/exa/ui/exams/new",
        "/exa/ui/lecturers/new",
        "/exa/ui/courses/",
        "/exa/ui/exams/",
        "/exa/ui/lecturers/"
      ]
    },
    "/exa/": {
      "filePath": "exa/index.lazy.tsx"
    },
    "/exa/ui/": {
      "filePath": "exa/ui/index.lazy.tsx"
    },
    "/exa/ui/courses/new": {
      "filePath": "exa/ui/courses/new.lazy.tsx"
    },
    "/exa/ui/exams/new": {
      "filePath": "exa/ui/exams/new.lazy.tsx"
    },
    "/exa/ui/lecturers/new": {
      "filePath": "exa/ui/lecturers/new.lazy.tsx"
    },
    "/exa/ui/courses/": {
      "filePath": "exa/ui/courses/index.lazy.tsx"
    },
    "/exa/ui/exams/": {
      "filePath": "exa/ui/exams/index.lazy.tsx"
    },
    "/exa/ui/lecturers/": {
      "filePath": "exa/ui/lecturers/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
