/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExaIndexLazyImport = createFileRoute('/exa/')()
const ExaUiIndexLazyImport = createFileRoute('/exa/ui/')()
const ExaUiLecturersLazyImport = createFileRoute('/exa/ui/lecturers')()
const ExaUiExamsLazyImport = createFileRoute('/exa/ui/exams')()
const ExaUiCoursesLazyImport = createFileRoute('/exa/ui/courses')()
const ExaUiAboutLazyImport = createFileRoute('/exa/ui/about')()

// Create/Update Routes

const ExaIndexLazyRoute = ExaIndexLazyImport.update({
  id: '/exa/',
  path: '/exa/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/index.lazy').then((d) => d.Route))

const ExaUiIndexLazyRoute = ExaUiIndexLazyImport.update({
  id: '/exa/ui/',
  path: '/exa/ui/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/ui/index.lazy').then((d) => d.Route))

const ExaUiLecturersLazyRoute = ExaUiLecturersLazyImport.update({
  id: '/exa/ui/lecturers',
  path: '/exa/ui/lecturers',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/lecturers.lazy').then((d) => d.Route),
)

const ExaUiExamsLazyRoute = ExaUiExamsLazyImport.update({
  id: '/exa/ui/exams',
  path: '/exa/ui/exams',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/ui/exams.lazy').then((d) => d.Route))

const ExaUiCoursesLazyRoute = ExaUiCoursesLazyImport.update({
  id: '/exa/ui/courses',
  path: '/exa/ui/courses',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/courses.lazy').then((d) => d.Route),
)

const ExaUiAboutLazyRoute = ExaUiAboutLazyImport.update({
  id: '/exa/ui/about',
  path: '/exa/ui/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/ui/about.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exa/': {
      id: '/exa/'
      path: '/exa'
      fullPath: '/exa'
      preLoaderRoute: typeof ExaIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/about': {
      id: '/exa/ui/about'
      path: '/exa/ui/about'
      fullPath: '/exa/ui/about'
      preLoaderRoute: typeof ExaUiAboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/courses': {
      id: '/exa/ui/courses'
      path: '/exa/ui/courses'
      fullPath: '/exa/ui/courses'
      preLoaderRoute: typeof ExaUiCoursesLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/exams': {
      id: '/exa/ui/exams'
      path: '/exa/ui/exams'
      fullPath: '/exa/ui/exams'
      preLoaderRoute: typeof ExaUiExamsLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/lecturers': {
      id: '/exa/ui/lecturers'
      path: '/exa/ui/lecturers'
      fullPath: '/exa/ui/lecturers'
      preLoaderRoute: typeof ExaUiLecturersLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/': {
      id: '/exa/ui/'
      path: '/exa/ui'
      fullPath: '/exa/ui'
      preLoaderRoute: typeof ExaUiIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/exa': typeof ExaIndexLazyRoute
  '/exa/ui/about': typeof ExaUiAboutLazyRoute
  '/exa/ui/courses': typeof ExaUiCoursesLazyRoute
  '/exa/ui/exams': typeof ExaUiExamsLazyRoute
  '/exa/ui/lecturers': typeof ExaUiLecturersLazyRoute
  '/exa/ui': typeof ExaUiIndexLazyRoute
}

export interface FileRoutesByTo {
  '/exa': typeof ExaIndexLazyRoute
  '/exa/ui/about': typeof ExaUiAboutLazyRoute
  '/exa/ui/courses': typeof ExaUiCoursesLazyRoute
  '/exa/ui/exams': typeof ExaUiExamsLazyRoute
  '/exa/ui/lecturers': typeof ExaUiLecturersLazyRoute
  '/exa/ui': typeof ExaUiIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/exa/': typeof ExaIndexLazyRoute
  '/exa/ui/about': typeof ExaUiAboutLazyRoute
  '/exa/ui/courses': typeof ExaUiCoursesLazyRoute
  '/exa/ui/exams': typeof ExaUiExamsLazyRoute
  '/exa/ui/lecturers': typeof ExaUiLecturersLazyRoute
  '/exa/ui/': typeof ExaUiIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/exa'
    | '/exa/ui/about'
    | '/exa/ui/courses'
    | '/exa/ui/exams'
    | '/exa/ui/lecturers'
    | '/exa/ui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/exa'
    | '/exa/ui/about'
    | '/exa/ui/courses'
    | '/exa/ui/exams'
    | '/exa/ui/lecturers'
    | '/exa/ui'
  id:
    | '__root__'
    | '/exa/'
    | '/exa/ui/about'
    | '/exa/ui/courses'
    | '/exa/ui/exams'
    | '/exa/ui/lecturers'
    | '/exa/ui/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ExaIndexLazyRoute: typeof ExaIndexLazyRoute
  ExaUiAboutLazyRoute: typeof ExaUiAboutLazyRoute
  ExaUiCoursesLazyRoute: typeof ExaUiCoursesLazyRoute
  ExaUiExamsLazyRoute: typeof ExaUiExamsLazyRoute
  ExaUiLecturersLazyRoute: typeof ExaUiLecturersLazyRoute
  ExaUiIndexLazyRoute: typeof ExaUiIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  ExaIndexLazyRoute: ExaIndexLazyRoute,
  ExaUiAboutLazyRoute: ExaUiAboutLazyRoute,
  ExaUiCoursesLazyRoute: ExaUiCoursesLazyRoute,
  ExaUiExamsLazyRoute: ExaUiExamsLazyRoute,
  ExaUiLecturersLazyRoute: ExaUiLecturersLazyRoute,
  ExaUiIndexLazyRoute: ExaUiIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/exa/",
        "/exa/ui/about",
        "/exa/ui/courses",
        "/exa/ui/exams",
        "/exa/ui/lecturers",
        "/exa/ui/"
      ]
    },
    "/exa/": {
      "filePath": "exa/index.lazy.tsx"
    },
    "/exa/ui/about": {
      "filePath": "exa/ui/about.lazy.tsx"
    },
    "/exa/ui/courses": {
      "filePath": "exa/ui/courses.lazy.tsx"
    },
    "/exa/ui/exams": {
      "filePath": "exa/ui/exams.lazy.tsx"
    },
    "/exa/ui/lecturers": {
      "filePath": "exa/ui/lecturers.lazy.tsx"
    },
    "/exa/ui/": {
      "filePath": "exa/ui/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
