/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ExaIndexLazyImport = createFileRoute('/exa/')()
const ExaUiIndexLazyImport = createFileRoute('/exa/ui/')()
const ExaUiLecturersIndexLazyImport = createFileRoute('/exa/ui/lecturers/')()
const ExaUiExamsIndexLazyImport = createFileRoute('/exa/ui/exams/')()
const ExaUiCoursesIndexLazyImport = createFileRoute('/exa/ui/courses/')()
const ExaUiLecturersNewLazyImport = createFileRoute('/exa/ui/lecturers/new')()
const ExaUiLecturersLecturerIdLazyImport = createFileRoute(
  '/exa/ui/lecturers/$lecturerId',
)()
const ExaUiExamsNewLazyImport = createFileRoute('/exa/ui/exams/new')()
const ExaUiExamsExamIdLazyImport = createFileRoute('/exa/ui/exams/$examId')()
const ExaUiCoursesNewLazyImport = createFileRoute('/exa/ui/courses/new')()
const ExaUiCoursesCourseIdLazyImport = createFileRoute(
  '/exa/ui/courses/$courseId',
)()
const ExaUiCoursesCourseIdIndexLazyImport = createFileRoute(
  '/exa/ui/courses/$courseId/',
)()
const ExaUiModuleNewCourseIdIndexLazyImport = createFileRoute(
  '/exa/ui/module/new/$courseId/',
)()
const ExaUiLectureNewCourseIdIndexLazyImport = createFileRoute(
  '/exa/ui/lecture/new/$courseId/',
)()

// Create/Update Routes

const ExaIndexLazyRoute = ExaIndexLazyImport.update({
  id: '/exa/',
  path: '/exa/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/index.lazy').then((d) => d.Route))

const ExaUiIndexLazyRoute = ExaUiIndexLazyImport.update({
  id: '/exa/ui/',
  path: '/exa/ui/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/exa/ui/index.lazy').then((d) => d.Route))

const ExaUiLecturersIndexLazyRoute = ExaUiLecturersIndexLazyImport.update({
  id: '/exa/ui/lecturers/',
  path: '/exa/ui/lecturers/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/lecturers/index.lazy').then((d) => d.Route),
)

const ExaUiExamsIndexLazyRoute = ExaUiExamsIndexLazyImport.update({
  id: '/exa/ui/exams/',
  path: '/exa/ui/exams/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/exams/index.lazy').then((d) => d.Route),
)

const ExaUiCoursesIndexLazyRoute = ExaUiCoursesIndexLazyImport.update({
  id: '/exa/ui/courses/',
  path: '/exa/ui/courses/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/courses/index.lazy').then((d) => d.Route),
)

const ExaUiLecturersNewLazyRoute = ExaUiLecturersNewLazyImport.update({
  id: '/exa/ui/lecturers/new',
  path: '/exa/ui/lecturers/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/lecturers/new.lazy').then((d) => d.Route),
)

const ExaUiLecturersLecturerIdLazyRoute =
  ExaUiLecturersLecturerIdLazyImport.update({
    id: '/exa/ui/lecturers/$lecturerId',
    path: '/exa/ui/lecturers/$lecturerId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/exa/ui/lecturers/$lecturerId.lazy').then((d) => d.Route),
  )

const ExaUiExamsNewLazyRoute = ExaUiExamsNewLazyImport.update({
  id: '/exa/ui/exams/new',
  path: '/exa/ui/exams/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/exams/new.lazy').then((d) => d.Route),
)

const ExaUiExamsExamIdLazyRoute = ExaUiExamsExamIdLazyImport.update({
  id: '/exa/ui/exams/$examId',
  path: '/exa/ui/exams/$examId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/exams/$examId.lazy').then((d) => d.Route),
)

const ExaUiCoursesNewLazyRoute = ExaUiCoursesNewLazyImport.update({
  id: '/exa/ui/courses/new',
  path: '/exa/ui/courses/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/courses/new.lazy').then((d) => d.Route),
)

const ExaUiCoursesCourseIdLazyRoute = ExaUiCoursesCourseIdLazyImport.update({
  id: '/exa/ui/courses/$courseId',
  path: '/exa/ui/courses/$courseId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/exa/ui/courses/$courseId.lazy').then((d) => d.Route),
)

const ExaUiCoursesCourseIdIndexLazyRoute =
  ExaUiCoursesCourseIdIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ExaUiCoursesCourseIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/exa/ui/courses/$courseId/index.lazy').then((d) => d.Route),
  )

const ExaUiModuleNewCourseIdIndexLazyRoute =
  ExaUiModuleNewCourseIdIndexLazyImport.update({
    id: '/exa/ui/module/new/$courseId/',
    path: '/exa/ui/module/new/$courseId/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/exa/ui/module/new/$courseId/index.lazy').then(
      (d) => d.Route,
    ),
  )

const ExaUiLectureNewCourseIdIndexLazyRoute =
  ExaUiLectureNewCourseIdIndexLazyImport.update({
    id: '/exa/ui/lecture/new/$courseId/',
    path: '/exa/ui/lecture/new/$courseId/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/exa/ui/lecture/new/$courseId/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exa/': {
      id: '/exa/'
      path: '/exa'
      fullPath: '/exa'
      preLoaderRoute: typeof ExaIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/': {
      id: '/exa/ui/'
      path: '/exa/ui'
      fullPath: '/exa/ui'
      preLoaderRoute: typeof ExaUiIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/courses/$courseId': {
      id: '/exa/ui/courses/$courseId'
      path: '/exa/ui/courses/$courseId'
      fullPath: '/exa/ui/courses/$courseId'
      preLoaderRoute: typeof ExaUiCoursesCourseIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/courses/new': {
      id: '/exa/ui/courses/new'
      path: '/exa/ui/courses/new'
      fullPath: '/exa/ui/courses/new'
      preLoaderRoute: typeof ExaUiCoursesNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/exams/$examId': {
      id: '/exa/ui/exams/$examId'
      path: '/exa/ui/exams/$examId'
      fullPath: '/exa/ui/exams/$examId'
      preLoaderRoute: typeof ExaUiExamsExamIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/exams/new': {
      id: '/exa/ui/exams/new'
      path: '/exa/ui/exams/new'
      fullPath: '/exa/ui/exams/new'
      preLoaderRoute: typeof ExaUiExamsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/lecturers/$lecturerId': {
      id: '/exa/ui/lecturers/$lecturerId'
      path: '/exa/ui/lecturers/$lecturerId'
      fullPath: '/exa/ui/lecturers/$lecturerId'
      preLoaderRoute: typeof ExaUiLecturersLecturerIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/lecturers/new': {
      id: '/exa/ui/lecturers/new'
      path: '/exa/ui/lecturers/new'
      fullPath: '/exa/ui/lecturers/new'
      preLoaderRoute: typeof ExaUiLecturersNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/courses/': {
      id: '/exa/ui/courses/'
      path: '/exa/ui/courses'
      fullPath: '/exa/ui/courses'
      preLoaderRoute: typeof ExaUiCoursesIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/exams/': {
      id: '/exa/ui/exams/'
      path: '/exa/ui/exams'
      fullPath: '/exa/ui/exams'
      preLoaderRoute: typeof ExaUiExamsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/lecturers/': {
      id: '/exa/ui/lecturers/'
      path: '/exa/ui/lecturers'
      fullPath: '/exa/ui/lecturers'
      preLoaderRoute: typeof ExaUiLecturersIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/courses/$courseId/': {
      id: '/exa/ui/courses/$courseId/'
      path: '/'
      fullPath: '/exa/ui/courses/$courseId/'
      preLoaderRoute: typeof ExaUiCoursesCourseIdIndexLazyImport
      parentRoute: typeof ExaUiCoursesCourseIdLazyImport
    }
    '/exa/ui/lecture/new/$courseId/': {
      id: '/exa/ui/lecture/new/$courseId/'
      path: '/exa/ui/lecture/new/$courseId'
      fullPath: '/exa/ui/lecture/new/$courseId'
      preLoaderRoute: typeof ExaUiLectureNewCourseIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/exa/ui/module/new/$courseId/': {
      id: '/exa/ui/module/new/$courseId/'
      path: '/exa/ui/module/new/$courseId'
      fullPath: '/exa/ui/module/new/$courseId'
      preLoaderRoute: typeof ExaUiModuleNewCourseIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ExaUiCoursesCourseIdLazyRouteChildren {
  ExaUiCoursesCourseIdIndexLazyRoute: typeof ExaUiCoursesCourseIdIndexLazyRoute
}

const ExaUiCoursesCourseIdLazyRouteChildren: ExaUiCoursesCourseIdLazyRouteChildren =
  {
    ExaUiCoursesCourseIdIndexLazyRoute: ExaUiCoursesCourseIdIndexLazyRoute,
  }

const ExaUiCoursesCourseIdLazyRouteWithChildren =
  ExaUiCoursesCourseIdLazyRoute._addFileChildren(
    ExaUiCoursesCourseIdLazyRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/exa': typeof ExaIndexLazyRoute
  '/exa/ui': typeof ExaUiIndexLazyRoute
  '/exa/ui/courses/$courseId': typeof ExaUiCoursesCourseIdLazyRouteWithChildren
  '/exa/ui/courses/new': typeof ExaUiCoursesNewLazyRoute
  '/exa/ui/exams/$examId': typeof ExaUiExamsExamIdLazyRoute
  '/exa/ui/exams/new': typeof ExaUiExamsNewLazyRoute
  '/exa/ui/lecturers/$lecturerId': typeof ExaUiLecturersLecturerIdLazyRoute
  '/exa/ui/lecturers/new': typeof ExaUiLecturersNewLazyRoute
  '/exa/ui/courses': typeof ExaUiCoursesIndexLazyRoute
  '/exa/ui/exams': typeof ExaUiExamsIndexLazyRoute
  '/exa/ui/lecturers': typeof ExaUiLecturersIndexLazyRoute
  '/exa/ui/courses/$courseId/': typeof ExaUiCoursesCourseIdIndexLazyRoute
  '/exa/ui/lecture/new/$courseId': typeof ExaUiLectureNewCourseIdIndexLazyRoute
  '/exa/ui/module/new/$courseId': typeof ExaUiModuleNewCourseIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/exa': typeof ExaIndexLazyRoute
  '/exa/ui': typeof ExaUiIndexLazyRoute
  '/exa/ui/courses/new': typeof ExaUiCoursesNewLazyRoute
  '/exa/ui/exams/$examId': typeof ExaUiExamsExamIdLazyRoute
  '/exa/ui/exams/new': typeof ExaUiExamsNewLazyRoute
  '/exa/ui/lecturers/$lecturerId': typeof ExaUiLecturersLecturerIdLazyRoute
  '/exa/ui/lecturers/new': typeof ExaUiLecturersNewLazyRoute
  '/exa/ui/courses': typeof ExaUiCoursesIndexLazyRoute
  '/exa/ui/exams': typeof ExaUiExamsIndexLazyRoute
  '/exa/ui/lecturers': typeof ExaUiLecturersIndexLazyRoute
  '/exa/ui/courses/$courseId': typeof ExaUiCoursesCourseIdIndexLazyRoute
  '/exa/ui/lecture/new/$courseId': typeof ExaUiLectureNewCourseIdIndexLazyRoute
  '/exa/ui/module/new/$courseId': typeof ExaUiModuleNewCourseIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/exa/': typeof ExaIndexLazyRoute
  '/exa/ui/': typeof ExaUiIndexLazyRoute
  '/exa/ui/courses/$courseId': typeof ExaUiCoursesCourseIdLazyRouteWithChildren
  '/exa/ui/courses/new': typeof ExaUiCoursesNewLazyRoute
  '/exa/ui/exams/$examId': typeof ExaUiExamsExamIdLazyRoute
  '/exa/ui/exams/new': typeof ExaUiExamsNewLazyRoute
  '/exa/ui/lecturers/$lecturerId': typeof ExaUiLecturersLecturerIdLazyRoute
  '/exa/ui/lecturers/new': typeof ExaUiLecturersNewLazyRoute
  '/exa/ui/courses/': typeof ExaUiCoursesIndexLazyRoute
  '/exa/ui/exams/': typeof ExaUiExamsIndexLazyRoute
  '/exa/ui/lecturers/': typeof ExaUiLecturersIndexLazyRoute
  '/exa/ui/courses/$courseId/': typeof ExaUiCoursesCourseIdIndexLazyRoute
  '/exa/ui/lecture/new/$courseId/': typeof ExaUiLectureNewCourseIdIndexLazyRoute
  '/exa/ui/module/new/$courseId/': typeof ExaUiModuleNewCourseIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/exa'
    | '/exa/ui'
    | '/exa/ui/courses/$courseId'
    | '/exa/ui/courses/new'
    | '/exa/ui/exams/$examId'
    | '/exa/ui/exams/new'
    | '/exa/ui/lecturers/$lecturerId'
    | '/exa/ui/lecturers/new'
    | '/exa/ui/courses'
    | '/exa/ui/exams'
    | '/exa/ui/lecturers'
    | '/exa/ui/courses/$courseId/'
    | '/exa/ui/lecture/new/$courseId'
    | '/exa/ui/module/new/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/exa'
    | '/exa/ui'
    | '/exa/ui/courses/new'
    | '/exa/ui/exams/$examId'
    | '/exa/ui/exams/new'
    | '/exa/ui/lecturers/$lecturerId'
    | '/exa/ui/lecturers/new'
    | '/exa/ui/courses'
    | '/exa/ui/exams'
    | '/exa/ui/lecturers'
    | '/exa/ui/courses/$courseId'
    | '/exa/ui/lecture/new/$courseId'
    | '/exa/ui/module/new/$courseId'
  id:
    | '__root__'
    | '/exa/'
    | '/exa/ui/'
    | '/exa/ui/courses/$courseId'
    | '/exa/ui/courses/new'
    | '/exa/ui/exams/$examId'
    | '/exa/ui/exams/new'
    | '/exa/ui/lecturers/$lecturerId'
    | '/exa/ui/lecturers/new'
    | '/exa/ui/courses/'
    | '/exa/ui/exams/'
    | '/exa/ui/lecturers/'
    | '/exa/ui/courses/$courseId/'
    | '/exa/ui/lecture/new/$courseId/'
    | '/exa/ui/module/new/$courseId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ExaIndexLazyRoute: typeof ExaIndexLazyRoute
  ExaUiIndexLazyRoute: typeof ExaUiIndexLazyRoute
  ExaUiCoursesCourseIdLazyRoute: typeof ExaUiCoursesCourseIdLazyRouteWithChildren
  ExaUiCoursesNewLazyRoute: typeof ExaUiCoursesNewLazyRoute
  ExaUiExamsExamIdLazyRoute: typeof ExaUiExamsExamIdLazyRoute
  ExaUiExamsNewLazyRoute: typeof ExaUiExamsNewLazyRoute
  ExaUiLecturersLecturerIdLazyRoute: typeof ExaUiLecturersLecturerIdLazyRoute
  ExaUiLecturersNewLazyRoute: typeof ExaUiLecturersNewLazyRoute
  ExaUiCoursesIndexLazyRoute: typeof ExaUiCoursesIndexLazyRoute
  ExaUiExamsIndexLazyRoute: typeof ExaUiExamsIndexLazyRoute
  ExaUiLecturersIndexLazyRoute: typeof ExaUiLecturersIndexLazyRoute
  ExaUiLectureNewCourseIdIndexLazyRoute: typeof ExaUiLectureNewCourseIdIndexLazyRoute
  ExaUiModuleNewCourseIdIndexLazyRoute: typeof ExaUiModuleNewCourseIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  ExaIndexLazyRoute: ExaIndexLazyRoute,
  ExaUiIndexLazyRoute: ExaUiIndexLazyRoute,
  ExaUiCoursesCourseIdLazyRoute: ExaUiCoursesCourseIdLazyRouteWithChildren,
  ExaUiCoursesNewLazyRoute: ExaUiCoursesNewLazyRoute,
  ExaUiExamsExamIdLazyRoute: ExaUiExamsExamIdLazyRoute,
  ExaUiExamsNewLazyRoute: ExaUiExamsNewLazyRoute,
  ExaUiLecturersLecturerIdLazyRoute: ExaUiLecturersLecturerIdLazyRoute,
  ExaUiLecturersNewLazyRoute: ExaUiLecturersNewLazyRoute,
  ExaUiCoursesIndexLazyRoute: ExaUiCoursesIndexLazyRoute,
  ExaUiExamsIndexLazyRoute: ExaUiExamsIndexLazyRoute,
  ExaUiLecturersIndexLazyRoute: ExaUiLecturersIndexLazyRoute,
  ExaUiLectureNewCourseIdIndexLazyRoute: ExaUiLectureNewCourseIdIndexLazyRoute,
  ExaUiModuleNewCourseIdIndexLazyRoute: ExaUiModuleNewCourseIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/exa/",
        "/exa/ui/",
        "/exa/ui/courses/$courseId",
        "/exa/ui/courses/new",
        "/exa/ui/exams/$examId",
        "/exa/ui/exams/new",
        "/exa/ui/lecturers/$lecturerId",
        "/exa/ui/lecturers/new",
        "/exa/ui/courses/",
        "/exa/ui/exams/",
        "/exa/ui/lecturers/",
        "/exa/ui/lecture/new/$courseId/",
        "/exa/ui/module/new/$courseId/"
      ]
    },
    "/exa/": {
      "filePath": "exa/index.lazy.tsx"
    },
    "/exa/ui/": {
      "filePath": "exa/ui/index.lazy.tsx"
    },
    "/exa/ui/courses/$courseId": {
      "filePath": "exa/ui/courses/$courseId.lazy.tsx",
      "children": [
        "/exa/ui/courses/$courseId/"
      ]
    },
    "/exa/ui/courses/new": {
      "filePath": "exa/ui/courses/new.lazy.tsx"
    },
    "/exa/ui/exams/$examId": {
      "filePath": "exa/ui/exams/$examId.lazy.tsx"
    },
    "/exa/ui/exams/new": {
      "filePath": "exa/ui/exams/new.lazy.tsx"
    },
    "/exa/ui/lecturers/$lecturerId": {
      "filePath": "exa/ui/lecturers/$lecturerId.lazy.tsx"
    },
    "/exa/ui/lecturers/new": {
      "filePath": "exa/ui/lecturers/new.lazy.tsx"
    },
    "/exa/ui/courses/": {
      "filePath": "exa/ui/courses/index.lazy.tsx"
    },
    "/exa/ui/exams/": {
      "filePath": "exa/ui/exams/index.lazy.tsx"
    },
    "/exa/ui/lecturers/": {
      "filePath": "exa/ui/lecturers/index.lazy.tsx"
    },
    "/exa/ui/courses/$courseId/": {
      "filePath": "exa/ui/courses/$courseId/index.lazy.tsx",
      "parent": "/exa/ui/courses/$courseId"
    },
    "/exa/ui/lecture/new/$courseId/": {
      "filePath": "exa/ui/lecture/new/$courseId/index.lazy.tsx"
    },
    "/exa/ui/module/new/$courseId/": {
      "filePath": "exa/ui/module/new/$courseId/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
