//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.19 at 12:32:39 AM CET 
//


package xmw.flush;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmw.flush package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmw.flush
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Courses }
     * 
     */
    public Courses createCourses() {
        return new Courses();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Faculty }
     * 
     */
    public Faculty createFaculty() {
        return new Faculty();
    }

    /**
     * Create an instance of {@link MaxStudents }
     * 
     */
    public MaxStudents createMaxStudents() {
        return new MaxStudents();
    }

    /**
     * Create an instance of {@link Exams }
     * 
     */
    public Exams createExams() {
        return new Exams();
    }

    /**
     * Create an instance of {@link Exam }
     * 
     */
    public Exam createExam() {
        return new Exam();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link IsOnline }
     * 
     */
    public IsOnline createIsOnline() {
        return new IsOnline();
    }

    /**
     * Create an instance of {@link IsWritten }
     * 
     */
    public IsWritten createIsWritten() {
        return new IsWritten();
    }

    /**
     * Create an instance of {@link RoomOrLink }
     * 
     */
    public RoomOrLink createRoomOrLink() {
        return new RoomOrLink();
    }

    /**
     * Create an instance of {@link Lecturers }
     * 
     */
    public Lecturers createLecturers() {
        return new Lecturers();
    }

    /**
     * Create an instance of {@link Lecturer }
     * 
     */
    public Lecturer createLecturer() {
        return new Lecturer();
    }

    /**
     * Create an instance of {@link Firstname }
     * 
     */
    public Firstname createFirstname() {
        return new Firstname();
    }

    /**
     * Create an instance of {@link Lectures }
     * 
     */
    public Lectures createLectures() {
        return new Lectures();
    }

    /**
     * Create an instance of {@link Lecture }
     * 
     */
    public Lecture createLecture() {
        return new Lecture();
    }

    /**
     * Create an instance of {@link Start }
     * 
     */
    public Start createStart() {
        return new Start();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link Semesters }
     * 
     */
    public Semesters createSemesters() {
        return new Semesters();
    }

    /**
     * Create an instance of {@link Semester }
     * 
     */
    public Semester createSemester() {
        return new Semester();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link Module }
     * 
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link Studies }
     * 
     */
    public Studies createStudies() {
        return new Studies();
    }

    /**
     * Create an instance of {@link Study }
     * 
     */
    public Study createStudy() {
        return new Study();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

}
