//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.18 at 02:31:18 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/namespace/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xmw.flush;
