//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.18 at 02:31:18 PM CET 
//


package xmw.flush;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{http://www.w3.org/namespace/}Courses"/&gt;
 *         &lt;element ref="{http://www.w3.org/namespace/}Exams"/&gt;
 *         &lt;element ref="{http://www.w3.org/namespace/}Lecturers"/&gt;
 *         &lt;element ref="{http://www.w3.org/namespace/}Lectures"/&gt;
 *         &lt;element ref="{http://www.w3.org/namespace/}Semesters"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coursesOrExamsOrLecturers"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElements({
        @XmlElement(name = "Courses", type = Courses.class),
        @XmlElement(name = "Exams", type = Exams.class),
        @XmlElement(name = "Lecturers", type = Lecturers.class),
        @XmlElement(name = "Lectures", type = Lectures.class),
        @XmlElement(name = "Semesters", type = Semesters.class)
    })
    protected List<Object> coursesOrExamsOrLecturers;

    /**
     * Gets the value of the coursesOrExamsOrLecturers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coursesOrExamsOrLecturers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoursesOrExamsOrLecturers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Courses }
     * {@link Exams }
     * {@link Lecturers }
     * {@link Lectures }
     * {@link Semesters }
     * 
     * 
     */
    public List<Object> getCoursesOrExamsOrLecturers() {
        if (coursesOrExamsOrLecturers == null) {
            coursesOrExamsOrLecturers = new ArrayList<Object>();
        }
        return this.coursesOrExamsOrLecturers;
    }

}
